### ISSUE TITLE
check out the API from OSF

### ISSUE THREAD

**Issue by hardyoyo** [eScholarship/EarthArXiv#1]
1. Create an account and obtain read token https://accounts.osf.io/login?service=https://osf.io/dashboard/
2. Review example usage app - https://github.com/eartharxiv/API/blob/master/downloadAndIndexPreprints.py#L66
3. Connect to the service and bring in data
4. Share the data on a dev server

**Comment by hardyoyo** [comment]
Issue was accidentally deleted during a reorganization of how we handle this project's code. Recreated from GitHub emails. I will copy/paste comments from the original issue below.

**Comment by hardyoyo** [comment]
from @myucekul on June 8, 2020:
> Blocking issue - the personal token generated allows access to the data in that account. Need appropriate token for access to EarthArXiv data.

**Comment by tingletech** [comment]
there is a copy of all the primary PDF or doc files on -dev.  @myucekul did you write a script to grab those?

I'm able to see the eartharxiv preprint data: Using the API in browser.
https://api.osf.io/v2/preprints/?filter[provider]=eartharxiv
I found the API documentation helpful. https://developer.osf.io/#
I'm able to see some user information.
https://api.osf.io/v2/nodes/hyksm/bibliographic_contributors/

examples with multiple versions
https://api.osf.io/v2/preprints/?filter%5Bid%5D=jwb5v

example with attached files:
___

**Comment by myucekul** [comment]
Yea, I have a script to download primary files.

**Comment by tingletech** [comment]
okay to close?

**Comment by hardyoyo** [comment]
Yes!
